public class HelloWorld {
public Wether vW;
    public HelloWorld() {
	    this.vW = Wether.SUMMer;
        system.debug('vWvADEVMac new version => '+vW);
        system.debug('second update from mavensmate'); 
        system.debug('I am working on that');
    }
    
    public enum Wether {SUMMER, WINTER}
    
    public static void methodHello(){
    	system.debug('hello');
    	system.debug('hello from mavensmate');
    	system.debug('new comment from mavensmate');
    	system.debug('new comment from eclipse');
    }
    
}